services:
  openclaw-gateway:
    user: "1500:1500"
    build:
      context: .
      dockerfile: Dockerfile.custom
    volumes:
      - /opt/openclaw/config:/home/node/.openclaw
      - /opt/openclaw/workspaces:/home/node/.openclaw/workspaces
      - /opt/openclaw/config/mcporter.json:/app/config/mcporter.json
      - /opt/obsidian/ob-vault:/home/node/obsidian-vault
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - NET_ADMIN
      - NET_RAW
    networks:
      - default
      - openclaw-internal
    deploy:
      resources:
        limits:
          memory: 900m
        reservations:
          memory: 256m

  openclaw-cli:
    user: "1500:1500"
    build:
      context: .
      dockerfile: Dockerfile.custom
      args:
        OPENCLAW_INSTALL_BROWSER: "1"
    volumes:
      - /opt/openclaw/config:/home/node/.openclaw
      - /opt/openclaw/workspaces:/home/node/.openclaw/workspaces
      - /opt/obsidian/ob-vault:/home/node/obsidian-vault
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 400m
        reservations:
          memory: 128m

networks:
  default:
    name: openclaw-src_default
  openclaw-internal:
    external: true
